version: '3.9'

services:
  php:
    container_name: zds-php
    build:
      context: .
    restart: always
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - zdsnet

  web:
    image: registry.docker.ir/nginx
    container_name: zds-nginx
    working_dir: /var/www/html
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker_config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker_config/nginx/ssl/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./docker_config/nginx/ssl/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
    depends_on:
      - php
      - db
    networks:
      - zdsnet

  db:
    image: registry.docker.ir/mariadb:10.6
    container_name: zds-db
    restart: always
    volumes:
      - ./docker_config/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=3Lb0LLV6A5y4
      - MYSQL_PASSWORD=3Lb0LLV6A5y4
      - MYSQL_DATABASE=zd
      - MYSQL_USER=zd
    networks:
      - zdsnet

  redis:
    image: registry.docker.ir/redis
    container_name: zds-redis
    restart: always
    volumes:
      - ./docker_config/redisdata:/data
    networks:
      - zdsnet
    
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: registry.docker.ir/phpmyadmin
    restart: always
    container_name: zds-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 3Lb0LLV6A5y4
    networks:
      - zdsnet
  
  supervisor:
    build:
      context: .
      dockerfile: supervisor.Dockerfile
    container_name: zds-supervisor
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - zdsnet

networks:
  zdsnet:
    name: zdsnet
    ipam:
      driver: default
      config:
       - subnet: '172.20.0.0/24'
       - gateway: '172.20.0.1'