version: '3'

services:
  php:
    build:
      context: .
    restart: always
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  web:
    image: nginx
    working_dir: /var/www/html
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker_config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  db:
    image: mariadb:10.6
    restart: always
    volumes:
      - ./docker_config/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=3Lb0LLV6A5y4
      - MYSQL_PASSWORD=3Lb0LLV6A5y4
      - MYSQL_DATABASE=zd
      - MYSQL_USER=zd

  redis:
    image: redis
    volumes:
      - ./docker_config/redisdata:/data