version: '3'

services:
  php:
    build:
      context: .
    restart: always
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  web:
    image: nginx
    working_dir: /var/www/html
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker_config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  db:
    image: mariadb:10.6
    restart: always
    volumes:
      - ./docker_config/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=3Lb0LLV6A5y4
      - MYSQL_PASSWORD=3Lb0LLV6A5y4
      - MYSQL_DATABASE=zd
      - MYSQL_USER=zd

  redis:
    image: redis
    restart: always
    volumes:
      - ./docker_config/redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 3Lb0LLV6A5y4